version: '3.8'

services:
  # MongoDB Database
  mongo:
    image: mongo:7.0
    container_name: mern_mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mern_boilerplate
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - mern-network

  # MongoDB Express (Optional - for database management)
  mongo-express:
    image: mongo-express:1.0.0
    container_name: mern_mongo_express
    restart: unless-stopped
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongo:27017/
      ME_CONFIG_BASICAUTH: false
    depends_on:
      - mongo
    networks:
      - mern-network

  # MERN Application
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mern_app
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://admin:password@mongo:27017/mern_boilerplate?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-for-docker
      JWT_EXPIRE: 30d
      CLIENT_URL: http://localhost:5000
    depends_on:
      - mongo
    volumes:
      - ./server:/app/server
      - /app/node_modules
    networks:
      - mern-network

  # Development version (with hot reload)
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mern_app_dev
    restart: unless-stopped
    ports:
      - "3000:3000"  # React dev server
      - "5000:5000"  # Express server
    environment:
      NODE_ENV: development
      PORT: 5000
      MONGO_URI: mongodb://admin:password@mongo:27017/mern_boilerplate?authSource=admin
      JWT_SECRET: your-super-secret-jwt-key-for-docker
      JWT_EXPIRE: 30d
      CLIENT_URL: http://localhost:3000
      CHOKIDAR_USEPOLLING: true
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules
    networks:
      - mern-network
    profiles:
      - dev

volumes:
  mongo_data:

networks:
  mern-network:
    driver: bridge